[botdetection]
    
[botdetection.ip_limit]
filter_link_local = true
# link_local_limit removed as it is not supported in this schema version
    
[botdetection.ip_lists]
pass_ip = [
    '127.0.0.0/8',       # Localhost
    '10.0.0.0/8',        # Private Netze (Docker)
    '172.16.0.0/12',     # Docker Standard Bridge
    '192.168.0.0/16',    # Heimnetzwerke
    '::1',               # IPv6 Localhost
    'fe80::/10',         # Link-local IPv6
]
